#include "drv_ctrl_mode.idl"
#include "drv_ctrl_error.idl"
#include "move_limit_state.idl"
#include "dcu_status.idl"
#include "transit_proc_status.idl"
#include "rotor_ang_sens_state.idl"
#include "load_ang_sens_state.idl"
#include "rotor_brake_state.idl"

@doc('Состояние привода наведения БУП')
struct bup_drv_state
{
    @doc('Способ управления приводом')
    @alias('drv_ctrl_mode')
    int8 mode;

    @doc('Код ошибки смены способа управления')
    @alias('drv_ctrl_error')
    int8 error;

    @doc('Состояние')
    @alias('dcu_status')
    int8 status;

    @doc('Признак ограничения наведения')
    @alias('move_limit_state')
    int8 limit;

    @doc('Угловое положение в локальной СК, рад. От -pi до pi')
    float angle;

    @doc('Угловая скорость в локальной СК, рад/с')
    float speed;

    @doc('Температра статора, C')
    float stator_temp;

    @doc('Состояние тормоза')
    @alias('rotor_brake_state')
    int8 brake_state;

    @doc('Напряжение питания модуля, В')
    float power_voltage;

    @doc('Ток id, А')
    float id;

    @doc('Ток iq, А')
    float iq;

    @doc('Мощность, положителная - потребляемая, отрицательная - генерируемая в сеть, Вт')
    float electrical_power;

    @doc('Состояние датчика углового положения нагрузки')
    @alias('load_ang_sens_status')
    int8 load_sens_state;

    @doc('Данные от датчика углового положения нагрузки, рад +-pi')
    float load_sens_angle;

    @doc('Угловая скорость датчика положения нагрузки, рад/с')
    float load_sens_speed;

    @doc('Состояние датчика углового положения ротора')
    @alias('rotor_ang_sens_status')
    int8 rotor_sens_state;

    @doc('Данные от датчика углового положения ротора, рад +-512pi')
    float rotor_sens_angle;

    @doc('Угловая скорость датчика положения ротора, рад/с')
    float rotor_sens_speed;
};