#include "drv_ctrl_sp.idl"

@doc('Управление приводами БУП')
struct bup_drv_multi_control
{
    @doc('Управленние левым передним тяговым приводом')
    drv_ctrl_sp lfd;

    @doc('Управленние левым задним тяговым приводом')
    drv_ctrl_sp lrd;

    @doc('Управленние левым рулевым приводом')
    drv_ctrl_sp lst;

    @doc('Управленние правым передним тяговым приводом')
    drv_ctrl_sp rfd;

    @doc('Управленние правым задним тяговым приводом')
    drv_ctrl_sp rrd;

    @doc('Управленние правым рулевым приводом')
    drv_ctrl_sp rst;
};