@doc("Типы комманд для исполнения устрйоством")
enum command_type{
	@doc("Программная перезагрузка")
	SWRESET,
	@doc("Сохранить параметры в ПЗУ")
	SAVEPRM,
	@doc("Установить текущее положение привода как нулевое")
	SET_HOME_POSITION,
	@doc("Установить текущее положение привода как верхний предел перемещения")
	SET_UP_LIMIT,
	@doc("Установить текущее положение привода как нижний предел перемещения")
	SET_DOWN_LIMIT,
	@doc("Установить нулевое положение ротора")
	SET_EL_ZERO,
	@doc("Сброс времени наработки")
	OPERATION_TIME_RESET,
	@doc("Сброс значения интегратора")
	INTEGRATOR_RESET,
	@doc("Перейти в режим обновления прикладного ПО")
	FIRMWARE_UPGRADE,
	@doc("Подтвердить успешное обновление прикладного ПО")
	FIRMWARE_VERIFY,
	@doc("Выполнить калибровку датчиков тока")
	CURRENT_SENSOR_CALIB
};