@doc('Состояние модуля управления приводами')
enum dcu_status
{
    @doc('Неизвестно')
    UNKNOWN,
    @doc('Выключен')
    OFF,
    @doc('Подготовка к работе')
    PREPARE,
    @doc('Калибровка датчиков тока')
    CUR_CALIB,
    @doc('Привода обесточены')
    DISARM,
    @doc('Осуществляется наведение приводов')
    ARM,
    @doc('Отказ')
    @value(-1)
    FAULT
};