@doc('Ошибка смены способа управления')
enum drv_ctrl_error 
{
    @doc('Неизвестная ошибка')
    UNKNOWN,
    @doc('Ошибки отсутствуют')
    NONE,
    @doc('Вращение заблокировано')
    BLOCK,
    @doc('Отсутствует сигнал включения')
    OFF,
    @doc('Нет питания')
    POWER,
    @doc('Отсутствуют сигналы управления')
    CTRL,
    @doc('Перегрузка')
    OLP,
    @doc('Превышение максимального тока привода')
    OCP,
    @doc('Защита от низкого напряжение')
    UVP,
    @doc('Защита от короткого замыкания')
    SCP,
    @doc('Неподдерживаемый режим')
    MODE,
    @doc('Защита инвертора')
    INV,
    @doc('Нет связи с датчиком угла нагрузки')
    LANG,
    @doc('Нет связи с датчиком угла ротора')
    RANG,
    @doc('Защита от перегрева')
    OHP,
    @doc('Отказ тормоза')
    BRAKE,
    @doc('Отказ датчика положения ротора')
    ROTOR_SENS,
    @doc('Ошибка подключения мотора')
    MCON,
    @doc('Сервисный режим работы')
    SERVICE
};