@doc('Способ управленяи приводом')
enum drv_ctrl_mode 
{
    @doc('Неизвестно')
    UNKNOWN,

    @doc('Управление не осуществляется, привод обесточен')
    OFF,

    @doc('Свободное вращение без управления приводами')
    FREEMOVE,

    @doc('Застопорено')
    HOLD,

    @doc('Приведение на заданный угол')
    ANGLE,

    @doc('Перемещение с заданной скоростью')
    SPEED,

    @doc('Вращение ротора с заданной скоростью')
    RSPEED,

    @doc('Прямое управление напряжением привода')
    VOLTAGE,

    @doc('Синхронный режим')
    SYNCHRO,

    @doc('Прямое управление током привода')
    CURRENT,

    @doc('Прямое управление напряжением фазы A')
    VOLTAGE_A,

    @doc('Прямое управление напряжением фазы B')
    VOLTAGE_B,

    @doc('Прямое управление напряжением фазы C')
    VOLTAGE_C
};