#include "drv_ctrl_mode.idl"

@doc('Сигналы управления приводом')
struct drv_ctrl_sp
{
    @doc('Режим управления приводом')
    drv_ctrl_mode mode;

    @doc('Целевое значение углового положения привода, СК зависит от режима управления, рад')
    float angle; 

    @doc('Целевое значение угловой скорости привода, СК зависит от режима управления, рад/с')
    float speed;

    @doc('Целевое значение напряжения, точка формирования зависит от режима управления, В')
    float voltage;

    @doc('Целевое значение тока, точка формирования зависит от режима управления, А')
    float current;
};