@doc("Электронный формуляр изделия")
struct formular_info {
  @doc("Обозначение СЧ.
  Формат обозначения определяет разработчик СЧ.
  Рекомендуемый формат обозначения: ХХХХ.123456.123-12.
  Обозначение СЧ представляется в строковом виде в кодировке CP866")
  char description[32];

  @doc("Заводской номер СЧ.
  Заводской номер представляется в строковом виде в кодировке CP866")
  char factory_number[32];

  @doc("Дата изготовления СЧ. Задается в формате HH:MM dd.mm.yyyy")
  char factory_date[32];

  @doc("Версия ПО СЧ.
  Формат номера версии ПО определяется разработчиком СЧ
  Версия ПО представляется в строковом виде в кодировке CP866")
  char software_version[32];

  @doc("Версия реализованного протокола.
  Формат номера версии протокола определяется разработчиком СЧ
  Версия реализованного протокола представляется в строковом виде в кодировке CP866")
  char protocol_version[32];

  @doc("Глобально уникальный идентификационый номер устройства.
  Формат определяется разработчиком СЧ
  Представляется в строковом виде в шестнадцатеричном формате
  пример: '0D01020A0BFF'")
  char GUID[32];

  @doc("Текущая наработка СЧ с момента первого включения, секунды")
  long operation_time;

  @doc("Контрольная сумма ПО. Формат: HEX")
  char software_checksum[64];
  
  @doc("Код блока')
  octet code;
};