@doc('Состояние датчиков Холла')
struct hall_sensor
{
    @doc('Логический уровень датчика Холла A')
    boolean a;

    @doc('Логический уровень датчика Холла B')
    boolean b;

    @doc('Логический уровень датчика Холла C')
    boolean c;
};
