@doc('Управление электроприводами имитатора BRO 3.0')
struct im_bro_drive_ctrl
{
    @doc('Напряжения, прикладываемые к якорю привода, В')
    float voltage[3];
    @doc('Признак включения источника напряжения')
    boolean  connected;
};