@doc('Режим работы инвертора')
enum inverter_mode 
{
    @doc('Неизвестно')
    UNKNOW,
    @doc('Выключен')
    OFF,
    @doc('Включен, готов к работе')
    OK,
    @doc('Подготовка к включению')
    ENABLING,
    @doc('Подготовка к выключению')
    DISABLING,
    @doc('Отказ')
    FAULT,
    @doc('Калибровка датчиков тока')
    CALIBRATION,
    @doc('Проверка подключения фаз')
    CONNECTION_CHECK
};