
@doc("Состояние датчика угла нагрузки")
enum load_ang_sens_status{
	@doc("Состояние неизвестно")
	@value(0) UNKNOW,
	@doc("Подготовка")
	PREPARE,
    @doc("Отсутствует")
	UNCONNECTED,
	@doc("Штатное функционирование")
	NORMAL,
    @doc("Ограничено исправен")
	WARNING,
	@doc("Неисправен")
	@value(-1) FAULT
};