@doc("Состояние ограничения перемещения приводов")
enum move_limit_state{
	@doc("Состояние неизвестно")
	@value(0) UNKNOW,
	@doc("Ограничение отсутствует - наведение в пределах ограничений")
	NONE,
    @doc("Достигнут верхний предел сектора наведения")
	LIMIT_UP,
	@doc("Достигнут нижний предел сектора наведения")
	LIMIT_DOWN
};