@doc("Состояние обработки запроса на отправку сообщения")
enum msg_state{
	@doc("Запрос принят")
	@value(0) CONFIRMED,
	@doc("Сообщение отправлено")
	SEND,
	@doc("Неподдерживаемый ID сообщения")
	@value(-1) WRONGCODE,
	@doc("Невозможно отправить переодическое сообщение")
	@value(-2) ISPERIODIC,
	@doc("Отправка невозможна")
	@value(-3) IMPOSSIBLE
};