@doc('Результат обработки запроса на чтение или запись параметра устрйоства')
enum parameter_status{
	@doc("Параметр отправлен или записан успешно")
	OK,
	@doc("Неизвестный параметр")
	@value(-1) UNKNOWPRM,
    @doc("Запись параметра не удалась")
	@value(-4) WRITE_FAILED,
    @doc("Параметр доступен только для чтения")
	@value(-5) READ_ONLY,
    @doc("Параметр не реализован")
	@value(-6) NOT_SUPPORTED
};