#include "parameter_status.idl"

@doc('Ответ на запрос параметра устройства')
struct parameter_answer
{
    @doc('ID запрошенного параметра')
    @alias('PRM_ID_FROM_SPEC')
    unsigned long id;
    @doc('Результат выполнения запроса')
    parameter_status ans;
    @doc('Значение параметра')
    @alias('FROM_PRM_SPEC')
    char val[32];
};