#include "rotor_ang_sens_status.idl"

@doc('Данные от датчика углового положения ротора')
struct rotor_ang_sens_state
{
  @doc("Угол [-pi..pi], рад")
  float angle;
  @doc("Состояние датчика")
  rotor_ang_sens_status status;
};