@doc('Состояние синхронизации')
enum sync_state
{
    @doc('Ошибка')
    @value(-1) FAILED,
    @doc('Синхронизация не производится')
    @value(0) FREERUN,
    @doc('В процессе синхронизации')
    UNSYNC,
    @doc('Синхронизировано')
    SYNC
};