
@doc("Состояние переходного процесса")

enum transit_proc_status {
	@doc("Состояние неизвестно")
	@value(0) UNKNOW,
	@doc("Переходной процесс отсутствует")
	NONE,
    @doc("Переходной процесс не завершен")
	INPROGRESS,
	@doc("Переходной процесс завершен")
	DONE
};